### PR TITLE
Use NSHashTable to avoid registering duplicate component/controller

### PR DESCRIPTION
**Pull request by supercfanx**
Currently, if we register the same component or controller twice (which could happen in certain cases when a new scope handle is created before the controller is resolved?), appearance callbacks will be invoked twice. Fix this by using a `NSHashTable` to store the component/controller.

### CODE REVIEW

**Comment by ocrickard** [comment]
Awesome, thanks for fixing this!

**Comment by ocrickard** [comment]
Merge when you're ready!

**Comment by supercfanx** [comment]
@facebook-github-bot shipit

**Comment by supercfanx** [comment]
@ocrickard I don't see a merge option here, maybe I don't have the privilege?

**Comment by dshahidehpour** [comment]
@facebook-github-bot shipit

**Comment by adamjernst** [comment]
@facebook-github-bot shipit

**Pull request merged**
