### PR TITLE
Add width to nav

### PR DESCRIPTION
**Pull request by spicyj**
Fixes alignment when the nav has long titles.

### CODE REVIEW

**Comment by ryanrhee** [comment]
Trying now, one sec.

**Comment by ryanrhee** [comment]
Verified this fixes the issue.

I pushed 1634fd15e2653005a1766ece84ca4fbb5e769f76 which fixes the issue in the short-term, so we can take our time making sure this is what we want (now longer titles will be split into two lines).

I'm personally fine w/ the change, but will defer to @adamjernst, @eczarny, and @ocrickard.

**Comment by ryanrhee** [comment]
(oh, and @natansh)

**Comment by spicyj** [comment]
240px looks like this:

image

The current longest text ("Break Out Composite Components") fits in 248px on my machine.

**Comment by eczarny** [comment]
Thanks @spicyj!

**Comment by ryanrhee** [comment]
we should probably merge & close this? @adamjernst

**Comment by spicyj** [comment]
@ryanrhee This is merged and closed. :)

**Comment by ryanrhee** [comment]
oh derp :D

**Pull request merged**
