### PR TITLE
Add call operator

### PR DESCRIPTION
**Pull request by ocrickard**
Based on https://github.com/facebook/componentkit/pull/683

I think it makes sense to add a call operator for component actions instead of using the send() function. This makes them feel like functions...

### CODE REVIEW

**Comment by ocrickard** [comment]
@facebook-github-bot import

**Comment by adamjernst** [comment]
whoa! cool

**Comment by eczarny** [comment]
Totally on board with this. Looks like a great way to clean up the API a bit.

**Comment by conradev** [comment]
Thoughts on making `CKComponentAction(NULL)()` a no-op? Because actions are optional for all of our components, we have a lot of code that looks like this:

```objc++
if (_action)
    _action.call(self/*, stuff */);
```

Excited to see this land!

**Comment by ocrickard** [comment]
OK, I think I'm going to drop this one. We can revive it later, should be a quick codemod, but I think there are some good arguments to not adding a call operator.

**Pull request closed without merging**
