### PR TITLE
[CKComponentAction] Support block based action promotion/demotion

### PR DESCRIPTION
**Pull request by hehe-wz**

### CODE REVIEW

**Comment by ocrickard** [comment]
Looks like the sample project is failing to build now.

**Comment by ocrickard** [comment]
Sorry I've been slow to review this. @adamjernst brought up that a currying approach is probably preferable, so I'd really like to consider going with that instead. I'm planning on implementing soonish.

**Comment by danzimm** [comment]
I have now implemented the currying approach you spoke of @ocrickard 

Just realized I should have had you on the diff - weih took care of the review for me

**Comment by ocrickard** [comment]
Alright, I believe this has been addressed for the demote side. We probably just need to remove the assert for promotion, it should be just fine.

**Pull request closed without merging**
