### PR TITLE
Only apply the remaining violation to flexible children

### PR DESCRIPTION
**Pull request by eczarny**
Turns out `CKStackLayoutComponent` was incorrectly applying the remaining violation to inflexible children. Not good. Instead the remaining violation should only be applied to flexible children that specify a flex grow factor.

### CODE REVIEW

**Comment by facebook-github-bot-2** [comment]
By analyzing the blame information on this pull request, we identified @ocrickard to be a potential reviewer.

**Comment by eczarny** [comment]
I'm going to import this change to kick off the internal snapshot tests.

@facebook-github-bot import

**Comment by eczarny** [comment]
I'll follow up with a snapshot test case tomorrow.

**Comment by adamjernst** [comment]
@facebook-github-bot shipit

**Comment by facebook-github-bot-6** [comment]
Thanks for importing. If you are an FB employee go to [Phabricator](https://phabricator.intern.facebook.com/D3896763) to review internal test results.

**Pull request merged**
