### PR TITLE
Fix Travis CI for good

### PR DESCRIPTION
**Pull request by eczarny**

### CODE REVIEW

**Comment by eczarny** [comment]
First run:

https://travis-ci.org/facebook/componentkit/builds/156704445

Looks like the logs are too long. WTF. I may need to add xcpretty back just to deal with that.

**Comment by eczarny** [comment]
The one nice thing about using a build matrix is we get parallel builds. Nice.

**Comment by eczarny** [comment]
I think this is getting close. I still need to fix the WildeGuess build but otherwise the ComponentKit and the ComponentKitAppleTV tests succeed.

**Comment by eczarny** [comment]
Okay, quick summary of where this is so far:

1. I replaced `carthage update` with `carthage bootstrap` so we don't actually update the tests dependencies; now Carthage just pulls down the versions we wants and builds them
2. I reintroduced xcpretty to help reduce the size of the build log, which is something that Travis CI complained about (and failed a build for)
3. I created a build matrix for the ComponentKit, ComponentKitAppleTV, and WildeGuess projects/targets; this gives us a bit more speed and a more obvious idea what failed

**Comment by eczarny** [comment]
Success: https://travis-ci.org/facebook/componentkit/builds/156836795

**Comment by ocrickard** [comment]
Looks reasonable to me.

**Pull request merged**
