### PR TITLE
Add userInfo

### PR DESCRIPTION
**Pull request by WENDERLYNE**
to have a way to pass along information of state update, for logging reason.

### CODE REVIEW

**Comment by facebook-github-bot-1** [comment]
Thank you for your pull request and welcome to our community. We require contributors to sign our Contributor License Agreement, and we don't seem to have you on file. In order for us to review and merge your code, please sign up at https://code.facebook.com/cla - and if you have received this in error or have any questions, please drop us a line at cla@fb.com. Thanks!

**Comment by adamjernst** [comment]
Thanks for the contribution! `userInfo` is already a field on the `CKTransactionalComponentDataSourceAppliedChanges` type. Just read that! Let me know if that isn't working for you.

**Comment by adamjernst** [comment]
Oh hey Wen :P

**Comment by WENDERLYNE** [comment]
Hi, Adam! This is actually very helpful. Thanks!!

**Pull request closed without merging**
