### PR TITLE
Upgrade Travis CI to Xcode 8.2

### PR DESCRIPTION
**Pull request by eczarny**

### CODE REVIEW

**Comment by ocrickard** [comment]
yayay

**Comment by ocrickard** [comment]
@facebook-github-bot shipit

**Comment by conradev** [comment]
I wonder if this will increase or decrease build times

**Comment by ocrickard** [comment]
Kicking CI. Looks like this may be flaky @eczarny

**Comment by eczarny** [comment]
I'll fix the failures. Looks like Xcode isn't having my device configuration.

**Comment by eczarny** [comment]
> I wonder if this will increase or decrease build times

I'd hope this reduces the amount of time jobs wait in the queue. I'm assuming there are more Xcode 8.2 hosts, but we'll find out.

**Comment by eczarny** [comment]
Looks like this may have been the issue:

https://github.com/travis-ci/travis-ci/issues/7031

Trying one of the mentioned workarounds.

**Comment by eczarny** [comment]
I have no idea why these builds take so long:

https://travis-ci.org/facebook/componentkit/builds/201569646

That's still in the queue. Compare that to my fork's build time:

https://travis-ci.org/eczarny/componentkit/builds/201569675

**Pull request merged**
