### PR TITLE
Provide a way to compare CKComponentContextContents objects

### PR DESCRIPTION
**Pull request by adamjernst**
Just do the easiest possible implementation here. Useful utility.

### CODE REVIEW

**Comment by adamjernst** [comment]
@facebook-github-bot import

**Comment by adamjernst** [comment]
@facebook-github-bot shipit

**Comment by indragiek** [comment]
@facebook-github-bot shipit

**Comment by ocrickard** [comment]
Build failures didn't have any logs. Kicking them off again.

**Comment by eczarny** [comment]
Tried restarting the CI jobs again. Not sure what's going on there.

**Comment by eczarny** [comment]
I fixed the build on master. I'm just going to merge this and fix forward if CI breaks.

**Pull request merged**
