### PR TITLE
Revert usage of slather

### PR DESCRIPTION
**Pull request by ocrickard**
This dependency on building and testing ComponentKit has blocked several engineers from contributing over the past couple of months. Code coverage is a good thing, and we want to have it, but the reality is that this is too fragile as integrated. Until we have a better solution, we should just revert this to unblock casual contributors.

Revert "README: Add Coveralls badge"

This reverts commit e1a60212eefd047f3252033d6236f0c7ca0255de.

Revert "Generate coverage stats using slather/Coveralls"

This reverts commit d942965412ad1080292f3b72dcde6347283b8bd6.

### CODE REVIEW

**Comment by adamjernst** [comment]
accepted!

**Comment by appleguy** [comment]
@ocrickard what were the cases of folks getting blocked by this?  Although Coveralls (data collected by slather) is not working (showing 0% coverage) since we went to Xcode 7 on Travis, it hasn't clearly interfered with anything.  Curious if it might be doing so for individuals in the community.

**Comment by modocache** [comment]
I'm not sure if AsyncDisplayKit shares this setup, but running `pod install` is necessary to develop ComponentKit. At that point, developers who're running an older version of the `cocoapods` gem would encounter a pretty nasty stack trace. The `slather` integration wasn't clearly documented, so this was a frustrating experience.

**Comment by modocache** [comment]
Oh, looks like AsyncDisplayKit has the same setup. I just tried the following:

```
~/AsyncDisplayKit $ gem install cocoapods
~/AsyncDisplayKit $ pod install
---------------------------------------------
Error loading the plugin with path `/Library/Ruby/Gems/2.0.0/gems/slather-1.7.0/lib/cocoapods_plugin.rb`.

Gem::LoadError - Unable to activate slather-1.7.0, because xcodeproj-0.28.2 conflicts with xcodeproj (~> 0.23.0)
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/specification.rb:2007:in `raise_if_conflicts'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/specification.rb:1176:in `activate'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems.rb:186:in `rescue in try_activate'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems.rb:183:in `try_activate'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:132:in `rescue in require'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:144:in `require'
/Library/Ruby/Gems/2.0.0/gems/slather-1.7.0/lib/cocoapods_plugin.rb:1:in `<top (required)>'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/Library/Ruby/Gems/2.0.0/gems/claide-0.9.1/lib/claide/command/plugin_manager.rb:106:in `safe_require'
/Library/Ruby/Gems/2.0.0/gems/claide-0.9.1/lib/claide/command/plugin_manager.rb:32:in `block in load_plugins'
/Library/Ruby/Gems/2.0.0/gems/claide-0.9.1/lib/claide/command/plugin_manager.rb:31:in `each'
/Library/Ruby/Gems/2.0.0/gems/claide-0.9.1/lib/claide/command/plugin_manager.rb:31:in `load_plugins'
/Library/Ruby/Gems/2.0.0/gems/claide-0.9.1/lib/claide/command.rb:304:in `block in run'
/Library/Ruby/Gems/2.0.0/gems/claide-0.9.1/lib/claide/command.rb:303:in `each'
/Library/Ruby/Gems/2.0.0/gems/claide-0.9.1/lib/claide/command.rb:303:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/command.rb:47:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/bin/pod:44:in `<top (required)>'
/usr/local/bin/pod:23:in `load'
/usr/local/bin/pod:23:in `<main>'
---------------------------------------------

Updating local specs repositories
Analyzing dependencies
Downloading dependencies
Installing FBSnapshotTestCase (1.8.1)
Installing OCMock (2.2.4)
Generating Pods project
Integrating client project
Sending stats
Sending stats
Pod installation complete! There are 2 dependencies from the Podfile and 2 total pods installed.
```

In the end I think we decided that `slather` didn't provide enough value to justify debugging issues like the above.

**Comment by ocrickard** [comment]
To be clear we love code coverage metrics and slather looks awesome. We just didn't have time to figure out a better integration just yet. We thought we would revert while we try and figure one out.

**Pull request merged**
