### PR TITLE
Add support for CKComponentBoundsAnimation to CKComponentHostingView

### PR DESCRIPTION
**Pull request by conradev**
Pretty self-explanatory! Let me know if there are any changes I need to make.

### CODE REVIEW

**Comment by adamjernst** [comment]
Ooh awesome. Lemme see.

**Comment by conradev** [comment]
Rebased against master!

**Comment by facebook-github-bot-5** [comment]
It's been a while since the last commit was reviewed and the labels show this pull request needs review. Based on the blame information for the files in this pull request we identified @eczarny as a potential reviewer. Could you take a look please or cc someone with more context?

**Comment by ocrickard** [comment]
Looks pretty reasonable to me on first look. @adamjernst should confirm though.

**Comment by ocrickard** [comment]
ping @adamjernst

**Comment by adamjernst** [comment]
Thanks @conradev !

**Pull request merged**
