### PR TITLE
Implement memoization for the CKTransactionalComponentDataSource

### PR DESCRIPTION
**Pull request by conradev**
This change was pretty straightforward to implement, let me know if you have any feedback!

### CODE REVIEW

**Comment by darknoon** [comment]
Thanks Conrad, this looks pretty straightforward. How have you tested it?

**Comment by conradev** [comment]
I've been testing it in our app [Workflow](https://workflow.is), and it works as expected thus far!

Could/should perhaps write tests for this.

**Comment by conradev** [comment]
Rebased against master!

**Comment by MDSilber** [comment]
@conradev sorry for the delay! I'll take a look at this soon and get back to you. Would love some tests around this if possible.

**Comment by conradev** [comment]
I just made this thread-safe for the occasions when components are built concurrently (happens as an edge case of the transactional data source)

**Comment by MDSilber** [comment]
@conradev sorry for the delay. This looks good to me, going to double check with a colleague and hopefully merge in the next day or two.

**Comment by ocrickard** [comment]
@mdsilber any update on this?

**Comment by facebook-github-bot-3** [comment]
It's been a while since the last commit was reviewed and the labels show this pull request needs review. Based on the blame information for the files in this pull request we identified @MDSilber as a potential reviewer. Could you take a look please or cc someone with more context?

**Comment by ocrickard** [comment]
This needs unit tests before we could merge. Changes look reasonable to me, but we do need full coverage of the memoization behavior specifically for the transactional datasource.

**Comment by ocrickard** [comment]
Alright, I'm closing this since it's gone awhile without update. Feel free to re-issue the pr with tests, and I'll review.

**Pull request closed without merging**
