### PR TITLE
Remove record mode left enabled in spec

### PR DESCRIPTION
**Pull request by itsthejb**
Hi all,

Just found this `recordMode` left enabled (by myself in #272) :blush: Removed.

### CODE REVIEW

**Comment by adamjernst** [comment]
Good find — but it looks like a snapshot needs re-recording. Take a look?

**Comment by itsthejb** [comment]
Ah! Ok, will do...

**Comment by ocrickard** [comment]
Looks like the build is still failing.

**Comment by itsthejb** [comment]
Yep - sorry wrestling a little with creating ref images for the right platform versions... Think I have it now

**Comment by itsthejb** [comment]
Ok, got it :wink:

**Comment by ocrickard** [comment]
Thanks @itsthejb !

**Pull request merged**
