### PR TITLE
Remove the work thread override assert

### PR DESCRIPTION
**Pull request by eczarny**
This assert isn't providing any meaningful signal.

### CODE REVIEW

**Comment by facebook-github-bot-7** [comment]
@eczarny updated the pull request - [view changes](https://github.com/facebook/componentkit/pull/648/files/e188dc592ad38343a9747713a92d1e68e26c1dcd..a7d48360914062b65ea141ee2def0597311aa813)

**Comment by ocrickard** [comment]
@facebook-github-bot shipit

**Comment by facebook-github-bot-3** [comment]
Thanks for importing. If you are an FB employee go to [Phabricator](https://phabricator.intern.facebook.com/D3888881) to review internal test results.

**Comment by eczarny** [comment]
Doesn't look like the bot will merge this. Merging now.

**Pull request merged**
