### PR TITLE
Add tvOS as a deployment target to the Podspec

### PR DESCRIPTION
**Pull request by eczarny**
I think this is all that needs to be done to support tvOS in the Podspec. I'll need to do a bit of testing to confirm though.

### CODE REVIEW

**Comment by ocrickard** [comment]
@eczarny is this still needed?

**Comment by eczarny** [comment]
Likely. I'm going to create a dummy tvOS app to see if this works. Figured if we support tvOS folks using CocoaPods should be able to use ComponentKit in a tvOS app.

**Comment by eczarny** [comment]
`pod lib lint` works so I'm going to merge so I can fully test in a dummy app.

**Comment by eczarny** [comment]
Confirmed that this works with a dummy app and the following Podfile:

```
platform :tvos, '9.2'

target 'DummyApp' do
  pod 'ComponentKit', :git => 'https://github.com/facebook/componentkit.git'
end
```

**Comment by eczarny** [comment]
Doh. For some reason I thought this was accepted. Sorry about that.

**Pull request merged**
