### PR TITLE
Changed iphone simulator number in the build script to 9.2

### PR DESCRIPTION
**Pull request by MDSilber**
This is so CI will compile code with generics

### CODE REVIEW

**Comment by adamjernst** [comment]
Nice. Can yo figure out how to make Travis work?

**Comment by natansh** [comment]
@MDSilber Have a look at https://docs.travis-ci.com/user/languages/objective-c/

Based on this, I think you'll have to specify both `iphonesimulator9.3` (I'd suggest going straight to 9.3) as well as `osx_image: xcode7.3`  in the `.travis.yml` file to allow it to work.

**Comment by natansh** [comment]
It's important to note that adding generics might break compatibility with previous SDK versions. I don't see that as a blocker, but something to be mindful of.

**Comment by MDSilber** [comment]
Weird git things, going to submit a new pull request

**Pull request closed without merging**
