### PR TITLE
Add generics to CKStatefulViewComponentController

### PR DESCRIPTION
**Pull request by conradev**

### CODE REVIEW

**Comment by ocrickard** [comment]
lgtm!

**Comment by ocrickard** [comment]
@facebook-github-bot shipit

**Comment by ryanrhee** [comment]
@ocrickard is this supposed to auto-merge?

**Comment by ocrickard** [comment]
It won't build internally without manually commandeering and fixing up the existing controllers that depend on the existing generics. I'll deal with it tomorrow.

**Comment by eczarny** [comment]
@ocrickard any updates here? I can take on the internal changes if you don't have the bandwidth.

**Comment by eczarny** [comment]
Oops. Didn't mean to request review. My bad.

I'm working on getting this merged.

**Comment by eczarny** [comment]
Landed internally. Merging.

**Pull request merged**
