### PR TITLE
Revert "Merge pull request #373 from eyeem/remount-transactional-data…

### PR DESCRIPTION
**Pull request by ocrickard**
…-source"

This reverts commit 120ae17c8782bcb0eba98afe6421d6ddd332f66a, reversing
changes made to 8185e76f51663976d49baf7d82ce9a0e54271acb.

### CODE REVIEW

**Comment by ocrickard** [comment]
@itsthejb this changed caused a flaky test failure. Reverting and putting back in your court to improve the tests. https://travis-ci.org/facebook/componentkit/builds/156580104

**Comment by itsthejb** [comment]
Ok!

**Comment by eczarny** [comment]
@ocriackrd feel free to merge once CI passes.

**Comment by eczarny** [comment]
CI failed due to the linker issue. I restarted the job.

**Pull request merged**
