### PR TITLE
Version 0.15

### PR DESCRIPTION
**Pull request by eczarny**

### CODE REVIEW

**Comment by eczarny** [comment]
Simple enough. I'll create the tag once merged and try and publish the CocoaPod.

I didn't update the README since `~> 0.14` should still apply.

**Comment by eczarny** [comment]
Actually. @ocrickard how about we go ahead and release 0.15 instead of 0.14.1? There are plenty of changes in this next release and what's remaining in the 0.15 milestone can probably go into 0.15.1.

**Comment by ocrickard** [comment]
Looks reasonable, though I'm no expert on cocoapods here? I'm cool with 0.15 being this tag. We have some more things for 0.16... soon!

**Comment by eczarny** [comment]
I'm basing these changes off of #468. For CocoaPods I should be able to follow the instructions here to publish the release:

https://guides.cocoapods.org/making/making-a-cocoapod.html#release

**Comment by eczarny** [comment]
I closed out the 0.15 milestone and moved outstanding issues to the 0.16 milestone.

Folks using Carthage should be able to upgrade while those using CocoaPods will need to wait a bit longer. I need to sort out some permissions issues with CocoaPods Trunk.

**Comment by eczarny** [comment]
Pushed 0.15 to CocoaPods:

https://cocoapods.org/pods/ComponentKit

```
pod trunk push ComponentKit.podspec
```

**Pull request merged**
