### PR TITLE
Fix issue in CKTextKitContext

### PR DESCRIPTION
**Pull request by cntrump**
call [layoutManager usedRectForTextContainer:textContainer] in performBlockWithLockedTextKitComponents method always return CGRectZero.

test code :
``` objc
    __block CGRect usedRect = CGRectZero;
    CKTextKitContext *context = [[CKTextKitContext alloc] initWithAttributedString:[[NSAttributedString alloc] initWithString:@"facebook"] lineBreakMode:NSLineBreakByWordWrapping maximumNumberOfLines:0 constrainedSize:CGSizeMake(200, CGFLOAT_MAX) layoutManagerFactory:nil];
    [context performBlockWithLockedTextKitComponents:^(NSLayoutManager *layoutManager, NSTextStorage *textStorage, NSTextContainer *textContainer) {
        usedRect = [layoutManager usedRectForTextContainer:textContainer];
    }];

    NSLog(@"usedRect:%@", NSStringFromCGRect(usedRect));
```

### CODE REVIEW

**Comment by alickbass** [comment]
Hi! Thanks a lot for submitting this PR! We are trying to fix the Travis CI failing builds and once we're there, I will review this one 😉

**Comment by cntrump** [comment]
``` objc
- (void)_calculateSize
{
  // Force glyph generation and layout, which may not have happened yet (and isn't triggered by
  // -usedRectForTextContainer:).
  [_context performBlockWithLockedTextKitComponents:^(NSLayoutManager *layoutManager, NSTextStorage *textStorage, NSTextContainer *textContainer) {
    [layoutManager ensureLayoutForTextContainer:textContainer];
  }];


  CGRect constrainedRect = {CGPointZero, _constrainedSize};
  __block CGRect boundingRect;
  [_context performBlockWithLockedTextKitComponents:^(NSLayoutManager *layoutManager, NSTextStorage *textStorage, NSTextContainer *textContainer) {
    boundingRect = [layoutManager usedRectForTextContainer:textContainer];
  }];

  // TextKit often returns incorrect glyph bounding rects in the horizontal direction, so we clip to our bounding rect
  // to make sure our width calculations aren't being offset by glyphs going beyond the constrained rect.
  boundingRect = CGRectIntersection(boundingRect, {.size = constrainedRect.size});

  _calculatedSize = [_shadower outsetSizeWithInsetSize:boundingRect.size];
}
```
@alickbass 
In function _calculateSize,  [layoutManager ensureLayoutForTextContainer:textContainer] is no longer necessary.

**Comment by cntrump** [comment]
if setAttributedString called before addLayoutManager,  the usedRectForTextContainer will give a wrong height, because the NSOriginalFont is missing, must call setAttributedString after addLayoutManager.
 I tested with chinese string: @"test 测试".

**Comment by cntrump** [comment]
test case updated.

**Pull request closed without merging**
