### PR TITLE
Remove residual CKAssertMainThread

### PR DESCRIPTION
**Pull request by kastiglione**
As far as I can tell, this assert isn't necessary.

### CODE REVIEW

**Comment by kastiglione** [comment]
cc @rohan-mehta

**Comment by kastiglione** [comment]
@benlodotcom I have a feeling you might weigh in on this one.

**Comment by adamjernst** [comment]
Definitely intentional at this point.

**Comment by kastiglione** [comment]
Because of other callers? I'm not seeing how this method itself needs an assert.

If callers, then the assert should be moved to those.

**Comment by adamjernst** [comment]
Defer to Ben Loulier.

**Comment by kastiglione** [comment]
@benlodotcom Some related discussion is in #71.

**Comment by benlodotcom** [comment]
Sounds good to me for the preparation queue, can you move the assert in `CKComponentDataSource` before merge though ?

**Comment by kastiglione** [comment]
@benlodotcom In the update, `CKComponentDataSource` tracks whether an enqueue is in progress, and will assert if two enqueues are run concurrently.

**Comment by adamjernst** [comment]
I'm actually tending more against this proposal because as I rewrite the DataSource, I want to use the main thread as a convenient synchronization point.

I could make it accept a "target queue" i suppose... Let's discuss in person.

**Comment by kastiglione** [comment]
Ah, I see. It seems the two off-main modes are at odds: concurrent use makes dispatching-to-main convenient, but serial use makes dispatching-to-main more ritual.

I'm not pushing for this, it's not currently affecting me. Ideally it'd be nice to not have to dispatch to main for the serial case, but not if it has brings problems for concurrent use.

**Comment by adamjernst** [comment]
Cool. Let's close for now. Once the "new" STM data source lands, we could make it take a target queue for all serialization, then mark that queue and require that all calls to it, and callbacks from it, happen on that queue.

**Pull request closed without merging**
