### PR TITLE
.xcodeproj: Enable ALL the warnings

### PR DESCRIPTION
**Pull request by modocache**
Turn on virtually every Clang warning available to us.

This still doens't catch the warnings emitted by `pod lib lint` for some reason
(see #378 for a list of warnings).

### CODE REVIEW

**Comment by adamjernst** [comment]
so good!

**Comment by modocache** [comment]
@adamjernst Looks like Travis tripped up when launching the simulator the first time this PR was built. I restarted it and it's green now. :point_up:

**Comment by modocache** [comment]
@adamjernst Had to restart the build a few times before Travis CI finally began launching the simulator properly. Looks like all the tests pass, though!

**Comment by modocache** [comment]
So good! But no merge?

**Pull request merged**
