### PR TITLE
Removed unused file reference

### PR DESCRIPTION
**Pull request by eczarny**

### CODE REVIEW

**Comment by eczarny** [comment]
@adamjernst is this good to merge? I think you forgot a label.

**Comment by ocrickard** [comment]
CI failed, can you rebase to kick off another build?

**Comment by ocrickard** [comment]
but otherwise looks fine to me.

**Comment by eczarny** [comment]
Kicked the CI job. Seems like a transient failure.

**Comment by ocrickard** [comment]
lol, why is our CI so slow here? Can we upgrade our travis speed somehow?

**Comment by eczarny** [comment]
@ocrickard the job was stuck in a queue for several hours but once I restarted the job it was scheduled almost immediately.

You can pay for Travis CI to get a bit more capacity (I think) though I have no idea what the story is for repositories in the FB organization.

**Pull request merged**
