### PR TITLE
Maximum number of lines is not correctly enforced

### PR DESCRIPTION
**Pull request by conradev**
I added a failing test to illustrate the issue. Will update the PR with a fix for the issue if I come up with one!

### CODE REVIEW

**Comment by adamjernst** [comment]
Good catch! Let me know if you come up with a solution.

**Comment by ocrickard** [comment]
Awesome, thanks for finding this!

**Comment by conradev** [comment]
Fixed by #566, should this test case (which I assume passes now) be merged in?

**Comment by adamjernst** [comment]
@conradev looks like @nscoding included your test in #566, so it's merged. Credit goes to you for finding this. Thank you!

**Pull request closed without merging**
