### PR TITLE
Random cleanup

### PR DESCRIPTION
**Pull request by eczarny**
I found and removed a couple unused resources:

1. An unused `InfoPlist.strings` file living in `ComponentKitTests`
2. Unused iOS 8 reference images living in `ComponentKitTests`

I'm not really sure what the `ComponentKitTests` reference images were used for originally but they haven't been touched in a couple years.

### CODE REVIEW

**Comment by ryanrhee** [comment]
Sure, why not :)

**Comment by eczarny** [comment]
Yessssss. Now I can try this out:

@facebook-github-bot shipit

**Comment by ryanrhee** [comment]
@facebook-github-bot shipit

**Comment by ryanrhee** [comment]
wait wut. what is this sorcery!?

**Comment by eczarny** [comment]
Ugh, I don't think it's working. Thought I set it up correctly.

**Comment by eczarny** [comment]
@facebook-github-bot shipit

**Comment by eczarny** [comment]
@facebook-github-bot shipit

**Comment by ryanrhee** [comment]
@facebook-github-bot shipit

**Comment by facebook-github-bot-9** [comment]
Thanks for importing. If you are an FB employee go to [Phabricator](https://phabricator.intern.facebook.com/D3878773) to review internal test results.

**Comment by ryanrhee** [comment]
wow this is amazeballs

**Comment by eczarny** [comment]
@facebook-github-bot shipit

**Pull request merged**
